name: muzzify
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_bloc: ^8.0.1
  auto_route: ^3.2.4
  freezed_annotation: ^1.1.0
  flutter_html: ^2.2.1
  dio: ^4.0.4

  get_it: ^7.2.0 
  injectable: ^1.5.3 # todo

  # firebase
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  firebase_storage: ^10.2.7
  
  hive: ^2.0.5 # todo
  hive_flutter: ^1.1.0

  just_audio: ^0.9.20
  audio_video_progress_bar: ^0.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.4
  hive_generator: ^1.1.2
  auto_route_generator: ^3.2.3


flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
      